// This file is auto-generated by specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getGameState(config: MatchConfigParams | null) : Promise<Result<MazeState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_state", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startMatch(player1Cmd: string, player2Cmd: string, player1WorkingDir: string | null, player2WorkingDir: string | null, player1AgentId: string, player2AgentId: string, config: MatchConfigParams | null, botOptions: MatchBotOptions | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_match", { player1Cmd, player2Cmd, player1WorkingDir, player2WorkingDir, player1AgentId, player2AgentId, config, botOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopMatch() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_match") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAnalysisTurn(position: AnalysisPosition | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_analysis_turn", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAnalysisTurn() : Promise<Result<StopAnalysisTurnResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_analysis_turn") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async advanceAnalysis(actions: AnalysisActions | null) : Promise<Result<AdvanceAnalysisResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("advance_analysis", { actions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadScanPaths() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_scan_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScanPaths(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_scan_paths", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverBots(paths: string[]) : Promise<DiscoveredBot[]> {
    return await TAURI_INVOKE("discover_bots", { paths });
},
async loadMatchConfig() : Promise<Result<MatchConfigParams, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_match_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveMatchConfig(config: MatchConfigParams) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_match_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeBot(runCommand: string, workingDir: string, agentId: string) : Promise<Result<BotProbeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_bot", { runCommand, workingDir, agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reserve one generation and return only after its session is genuinely
 * live. The returned snapshot is authoritative; the matching event is
 * enrichment for other windows and background navigation.
 */
async startTournament(params: LaunchParams) : Promise<Result<TournamentStartedEvent, StartTournamentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_tournament", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request the owning generation to stop and wait until its finalizer has
 * persisted the terminal outcome and released the slot.
 */
async stopTournament() : Promise<Result<TournamentRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_tournament") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Frontend-confirmed native close. Uses a distinct durable reason and a
 * bounded drain so unfinished work is never presented as resumable.
 */
async shutdownTournament() : Promise<Result<TournamentRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shutdown_tournament") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current app-owned runner phase. Durable lifecycle remains on tournament
 * snapshots; this survives navigation/reload and exposes Starting/Stopping.
 */
async tournamentStatus() : Promise<Result<TournamentRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tournament_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List tournaments in the store, newest first, projected from durable
 * lifecycle plus the shared execution counters.
 */
async listTournaments() : Promise<Result<TournamentSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tournaments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Standings for one tournament, reopened from the store (read-only). Used for
 * finished tournaments and interrupted ones (standings-so-far).
 */
async getTournamentStandings(tournamentId: number) : Promise<Result<StandingsSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tournament_standings", { tournamentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reopen one tournament as a complete read model. This is also the durable
 * reconciliation endpoint for a running tournament: event delivery keeps the
 * UI immediate, while this snapshot repairs any lifecycle event a lagging
 * broadcast receiver missed.
 */
async getTournamentSnapshot(tournamentId: number) : Promise<Result<TournamentSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tournament_snapshot", { tournamentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Final-position board + verdict for one game, read from its `ReplayFile`.
 * Returns `Missing` (not an error) only when the file is absent. Permission,
 * read, and parse failures stay errors so the UI can distinguish lost
 * evidence from evidence it currently cannot read.
 */
async getGameReplay(tournamentId: number, matchId: number) : Promise<Result<GameReplayState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_replay", { tournamentId, matchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch-form defaults the frontend pre-fills from: the ladder recipe as a
 * factory config plus the methodology knobs. Derived from the Rust constants
 * (and the actual preset), so there's no TS mirror to drift.
 */
async getTournamentLaunchDefaults() : Promise<Result<LaunchDefaults, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tournament_launch_defaults") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
botInfoEvent: BotInfoEvent,
matchErrorEvent: MatchErrorEvent,
matchOverEvent: MatchOverEvent,
matchStartedEvent: MatchStartedEvent,
nowPlayingEvent: NowPlayingEvent,
preprocessingStartedEvent: PreprocessingStartedEvent,
setupCompleteEvent: SetupCompleteEvent,
standingsUpdatedEvent: StandingsUpdatedEvent,
tournamentAbortedEvent: TournamentAbortedEvent,
tournamentFinishedEvent: TournamentFinishedEvent,
tournamentMatchFailedEvent: TournamentMatchFailedEvent,
tournamentMatchFinishedEvent: TournamentMatchFinishedEvent,
tournamentMatchStartedEvent: TournamentMatchStartedEvent,
tournamentPreparingEvent: TournamentPreparingEvent,
tournamentStartedEvent: TournamentStartedEvent,
tournamentStoppingEvent: TournamentStoppingEvent,
turnPlayedEvent: TurnPlayedEvent
}>({
botInfoEvent: "bot-info-event",
matchErrorEvent: "match-error-event",
matchOverEvent: "match-over-event",
matchStartedEvent: "match-started-event",
nowPlayingEvent: "now-playing-event",
preprocessingStartedEvent: "preprocessing-started-event",
setupCompleteEvent: "setup-complete-event",
standingsUpdatedEvent: "standings-updated-event",
tournamentAbortedEvent: "tournament-aborted-event",
tournamentFinishedEvent: "tournament-finished-event",
tournamentMatchFailedEvent: "tournament-match-failed-event",
tournamentMatchFinishedEvent: "tournament-match-finished-event",
tournamentMatchStartedEvent: "tournament-match-started-event",
tournamentPreparingEvent: "tournament-preparing-event",
tournamentStartedEvent: "tournament-started-event",
tournamentStoppingEvent: "tournament-stopping-event",
turnPlayedEvent: "turn-played-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AdvanceAnalysisResult = { player1_action: Direction; player2_action: Direction; game_over: boolean }
/**
 * Pair of player actions for `advance_analysis`. Both must be provided together.
 */
export type AnalysisActions = { player1: Direction; player2: Direction }
/**
 * Arbitrary game-tree position for cursor-follows-analysis.
 */
export type AnalysisPosition = { turn: number; player1: PlayerState; player2: PlayerState; cheese: Coord[]; player1_last_move: Direction; player2_last_move: Direction }
/**
 * Bot debug/analysis info forwarded from the host event stream.
 */
export type BotInfoEvent = { match_id: number; sender: PlayerSide; subject: PlayerSide; turn: number; state_hash: string; multipv: number; target: Coord | null; depth: number; nodes: number; score: number | null; pv: Direction[]; message: string }
export type BotOptionDef = { name: string; option_type: BotOptionType; default_value: string; min: number; max: number; choices: string[] }
export type BotOptionType = "Check" | "Spin" | "Combo" | "String" | "Button"
/**
 * A single option name-value pair for configuring a bot before match start.
 */
export type BotOptionValue = { name: string; value: string }
/**
 * One bot selected on the launch screen. `agent_id` is the stable bot.toml id
 * and doubles as the tournament-scoped player id.
 */
export type BotPick = { agent_id: string; display_name: string; run_command: string; working_dir: string; declared_version: string | null;
/**
 * SHA-256 of the discovery-time `bot.toml`; identifies the launch
 * manifest only, not mutable files or a compiled executable.
 */
manifest_sha256: string | null }
export type BotProbeResult = { name: string; author: string; agent_id: string; options: BotOptionDef[] }
export type Coord = { x: number; y: number }
/**
 * Movement direction — specta-friendly mirror of pyrat_wire::Direction.
 */
export type Direction = "Up" | "Right" | "Down" | "Left" | "Stay"
export type DiscoveredBot = { agent_id: string; name: string; run_command: string;
/**
 * Absolute path to the directory containing bot.toml.
 */
working_dir: string; description: string; developer: string; language: string; tags: string[];
/**
 * Optional version declared by the manifest author.
 */
declared_version: string | null;
/**
 * SHA-256 of the exact `bot.toml` bytes. This identifies the manifest,
 * not the mutable source tree or compiled executable.
 */
manifest_sha256: string }
/**
 * Category of a match failure, for the per-bot health summary. Mirrors
 * `pyrat_eval::orchestrator::FailureReason` collapsed to what the UI groups on
 * (payload strings dropped; the implicated bot rides `failing_player_id`).
 */
export type FailureKind = "timeout" | "disconnected" | "spawn_failed" | "handshake_timeout" | "protocol_error" | "cancelled" |
/**
 * Tournament-infrastructure failure (panic, result-sink flush, internal),
 * not the bot's fault — kept distinct from `Other` so the UI doesn't read
 * an infra bug as "the bot failed".
 */
"internal" | "other"
/**
 * The game-instance distribution configured on the launch screen: board,
 * maze, start strategy, cheese. This is the *distribution*; the tournament
 * seed that selects which instances get drawn lives on `LaunchParams`.
 * Integer-like wire fields intentionally arrive as `f64`: JavaScript has one
 * numeric type, and accepting the raw value lets the command return a typed
 * field error for `7.5` instead of failing in Tauri deserialization.
 */
export type GameFactoryConfig = { width: number; height: number; max_turns: number; wall_density: number; mud_density: number; mud_range: number; connected: boolean; symmetric: boolean; player_start: PlayerStart; cheese_count: number; cheese_symmetric: boolean }
/**
 * Final-position board + verdict for one finished game, or a reason it's
 * unavailable (failed match, or replay file missing).
 */
export type GameReplayState = { kind: "available"; final_state: MazeState; winner: string | null; player1_id: string; player2_id: string; player1_score: number; player2_score: number; turns: number } | { kind: "missing"; reason: string }
/**
 * Launch-form defaults: the ladder recipe as a factory config plus the
 * methodology knobs. The frontend pre-fills from this, so the Rust constants
 * stay the single source of truth (no stale TS mirror to drift).
 */
export type LaunchDefaults = { factory: GameFactoryConfig; mazes_per_matchup: number; move_timeout_ms: number; preprocessing_timeout_ms: number; max_parallel: number; limits: LaunchLimits }
/**
 * One field-addressable launch validation failure.
 */
export type LaunchFieldError = { field: string; message: string }
/**
 * Backend-owned bounds for launch controls. The frontend uses these for
 * affordances; the validation boundary below remains authoritative.
 */
export type LaunchLimits = { min_dimension: number; max_dimension: number; max_turns: number; max_mud_range: number; max_cheese_count: number; max_participants: number; max_mazes_per_matchup: number; max_total_games: number; max_timeout_ms: number; max_parallel: number; max_js_safe_seed: number }
/**
 * Launch parameters. The factory + methodology knobs are configured on the
 * launch screen; the frontend pre-fills them from `get_tournament_launch_defaults`.
 * Methodology numbers likewise stay raw until `validate_launch_params`
 * proves they are finite whole values in range and narrows them to `u32`.
 */
export type LaunchParams = { bots: BotPick[];
/**
 * The starred bot to measure → gauntlet. `None` → round-robin.
 */
target: string | null; name: string | null;
/**
 * The game-instance distribution (board / maze / starts / cheese).
 */
factory: GameFactoryConfig;
/**
 * Mazes per matchup; the paired schedule runs 2× this many games.
 */
mazes_per_matchup: number; move_timeout_ms: number; preprocessing_timeout_ms: number; max_parallel: number;
/**
 * Tournament seed (selects which instances are drawn). `None` → random,
 * capped to the JS-safe range so it round-trips for reproducibility.
 */
tournament_seed: number | null }
/**
 * Per-player option overrides + match flags, bundled so start_match stays under specta's 10-arg limit.
 */
export type MatchBotOptions = { player1?: BotOptionValue[]; player2?: BotOptionValue[];
/**
 * When true, run in analysis (step-by-step) mode instead of auto-play.
 */
step_mode?: boolean }
export type MatchConfigParams = {
/**
 * Named preset, or "custom" for manual configuration.
 */
preset: string; width: number; height: number; max_turns: number; wall_density: number; mud_density: number; mud_range: number; connected: boolean; symmetric: boolean; cheese_count: number; cheese_symmetric: boolean;
/**
 * "corners" or "random".
 */
player_start: string;
/**
 * Seed for RNG. None = OS entropy.
 */
seed: number | null }
/**
 * Emitted on setup failures, bot crashes, etc.
 */
export type MatchErrorEvent = { match_id: number; message: string }
/**
 * Emitted when the match ends normally.
 */
export type MatchOverEvent = { match_id: number; winner: MatchWinner; player1_score: number; player2_score: number; turns_played: number }
/**
 * Full initial state so the frontend can initialize the renderer.
 */
export type MatchStartedEvent = { match_id: number; maze: MazeState }
export type MatchWinner = "Player1" | "Player2" | "Draw"
export type MazeState = { width: number; height: number; turn: number; max_turns: number; walls: WallEntry[]; mud: MudEntry[]; cheese: Coord[]; player1: PlayerState; player2: PlayerState; total_cheese: number; state_hash: string }
export type MudEntry = { from: Coord; to: Coord; cost: number }
/**
 * Throttled per-turn liveness from `live_events()` (slice B). Drives the
 * now-playing line and the depth-2 live-game row. Lossy by design.
 */
export type NowPlayingEvent = { tournament_id: number; match_id: number; turn: number; player1_score: number; player2_score: number }
/**
 * A participant, for the launch→live handoff (name + display fields).
 */
export type PlayerLite = { player_id: string }
/**
 * Player identity — specta-friendly mirror of pyrat_wire::Player.
 */
export type PlayerSide = "Player1" | "Player2"
/**
 * Player start strategy for the game-instance factory. Mirrors the engine's
 * `PlayerStrategy` (corners | random); fixed positions are parked.
 */
export type PlayerStart = "corners" | "random"
export type PlayerState = { position: Coord; score: number; mud_turns: number }
/**
 * Emitted when all bots enter the preprocessing phase.
 */
export type PreprocessingStartedEvent = { match_id: number }
export type RatingReadiness = "legacy_unknown" | "provisional" | "rateable" | "insufficient_games" | "disconnected_graph" | "estimator_failed"
/**
 * Emitted when setup is fully complete (bots connected, configured, preprocessed).
 */
export type SetupCompleteEvent = { match_id: number }
/**
 * One row of the live standings: Elo with an uncertainty band and game count.
 * Bounds come from `compute_elo_with_uncertainty` (point Elo alone has no
 * uncertainty information), so the frontend never reconstructs them or
 * promises a stronger statistical interpretation than the model supports.
 */
export type StandingRow = { player_id: string;
/**
 * No numeric placeholder is emitted when the estimator has no result.
 */
elo: number | null; elo_ci_low: number | null; elo_ci_high: number | null; games: number;
/**
 * True before the player has enough games for a stable estimate; the
 * frontend shows "warming up" instead of a bar.
 */
pending: boolean }
/**
 * Standings for a finished/partial tournament, reopened from the store.
 */
export type StandingsSnapshot = { tournament_id: number; name: string | null; format: string; anchor_id: string | null; lifecycle: TournamentLifecycleStatus; terminal: TournamentTerminalState | null; rating_readiness: RatingReadiness; rating_reason: string | null; progress: TournamentProgress; standings: StandingRow[] }
/**
 * Emitted on every `MatchFinished`, carrying the freshly recomputed standings
 * plus progress. The hero, standings bars/whiskers, progress, ETA, and chip
 * all read this.
 */
export type StandingsUpdatedEvent = { tournament_id: number; progress: TournamentProgress; rating_readiness: RatingReadiness; rating_reason: string | null; standings: StandingRow[] }
/**
 * Start errors keep form mistakes structured while preserving ordinary
 * runtime failures as a single message.
 */
export type StartTournamentError = { kind: "validation"; errors: LaunchFieldError[] } | { kind: "runtime"; message: string }
export type StopAnalysisTurnResult = { player1_action: Direction; player2_action: Direction }
/**
 * One durable successful attempt. Canonical player ids/scores stay stable
 * across the two seat-swapped legs; `rat_id` makes the actual seat visible.
 */
export type StoredFinishedGame = { attempt_id: number;
/**
 * Absent on rows written before migration 6. Those results remain
 * inspectable, but have no direct replay link.
 */
match_id: number | null; player1_id: string; player2_id: string; repetition_index: number; rat_id: string; player1_score: number; player2_score: number }
export type StoredInstancePolicy = "independent_per_slot" | "shared_maze_per_seat_pair"
/**
 * One durable failed attempt, retained in historical tournament inspection.
 */
export type StoredMatchFailure = { attempt_id: number; match_id: number | null; player1_id: string; player2_id: string; repetition_index: number; attempt_index: number; rat_id: string; failing_player_id: string | null; kind: FailureKind; timeout_phase: TimeoutPhase | null; reason: string;
/**
 * This failure spent the slot's final retry budget. Earlier failures on
 * the same slot remain inspectable but are not terminal legs.
 */
exhausted: boolean }
export type StoredOptionAssignment = { kind: "defaults" } | { kind: "explicit"; values: ([string, string])[] }
export type StoredParticipantFingerprint = { kind: string; value: string }
export type StoredParticipantLaunchSpec = { player_id: string; agent_id: string; display_name: string; command: string | null; working_dir: string | null; options: StoredOptionAssignment; declared_version: string | null; fingerprint: StoredParticipantFingerprint | null }
export type StoredSeatPolicy = "legacy" | "paired"
/**
 * Durable state of one expected schedule leg. `Running` is expressible for
 * live projections; store-only snapshots normally return `Pending` until a
 * terminal attempt lands. Old rows never have missing legs relabeled as
 * pending because their lifecycle is unknowable.
 */
export type StoredSlotState = { state: "successful"; attempt_id: number; match_id: number | null } | { state: "exhausted"; last_failure_attempt_id: number; failed_attempts: number } | { state: "pending" } | { state: "running"; match_id: number } | { state: "legacy_unknown" }
/**
 * Wire-safe projection of the store-native timing mode.
 */
export type StoredTimingMode = "wait" | "clock"
export type StoredTournamentInterpretation = { methodology_version: number; anchor_id: string; anchor_elo: number; estimator: string; estimator_version: number; draw_weight: number; prior_games: number; max_iterations: number; tolerance: number; min_games_per_player: number; uncertainty: string; instance_policy: StoredInstancePolicy }
/**
 * Durable execution conditions for a tournament. Kept as one optional
 * object: a missing object means the pre-migration row did not record any of
 * these values, rather than inheriting today's launch defaults.
 */
export type StoredTournamentMethodology = { timing_mode: StoredTimingMode; move_timeout_ms: number; preprocessing_timeout_ms: number; startup_timeout_ms: number; configure_timeout_ms: number; network_grace_ms: number; max_parallel: number }
export type StoredTournamentSlot = { player1_id: string; player2_id: string; repetition_index: number; rat_id: string; state: StoredSlotState }
/**
 * Which phase a timeout fired in, for labeling bot health
 * ("move timeout" vs "preprocessing").
 */
export type TimeoutPhase = "setup" | "preprocessing" | "sync" | "move"
/**
 * Terminal: tournament aborted (e.g. persistent sink-flush failure, or
 * user-requested stop). Carries a reason for the UI.
 */
export type TournamentAbortedEvent = { tournament_id: number; lifecycle: TournamentLifecycleStatus; reason: string; terminal: TournamentTerminalState; rating_readiness: RatingReadiness }
/**
 * Terminal: tournament finished naturally. The hero swaps to the verdict and
 * the chip goes green.
 */
export type TournamentFinishedEvent = { tournament_id: number; terminal: TournamentTerminalState; rating_readiness: RatingReadiness }
/**
 * Durable lifecycle projected without inference. Old rows remain
 * `legacy_unknown`; the app-owned `running` flag is a separate live fact.
 */
export type TournamentLifecycleStatus = "legacy_unknown" | "preparing" | "running" | "completed" | "stopped" | "failed"
/**
 * Terminal, per-match: a match failed (timeout, disconnect, spawn failure).
 * Verdict-bearing data (the success/failure tally) still rides the lossless
 * standings path; this also carries enough to (a) drop the now-playing row
 * and (b) accumulate per-bot health. Distinct from
 * `TournamentMatchFinishedEvent`, which means a *successful scored game* (form
 * dots, game cards, replay).
 */
export type TournamentMatchFailedEvent = { tournament_id: number; match_id: number;
/**
 * Canonical pair (player1_id = lex-min), so the frontend can attribute the
 * failure to a matchup without a lookup.
 */
player1_id: string; player2_id: string; repetition_index: number; attempt_index: number;
/**
 * Canonical player id occupying the Rat seat in this failed leg.
 */
rat_id: string;
/**
 * The bot the failure points at (timeout / clean disconnect), resolved
 * from the engine seat via the match's seat orientation. `None` for
 * structural failures (spawn, sink, internal) with no single seat.
 */
failing_player_id: string | null; kind: FailureKind;
/**
 * Set only when `kind == Timeout`.
 */
timeout_phase: TimeoutPhase | null;
/**
 * Stable durable failure text retained for later inspection.
 */
reason: string;
/**
 * True only when this durable failure spent the slot's retry budget.
 */
exhausted: boolean }
/**
 * Emitted on every `MatchFinished`. Scores are canonical (player1_id is the
 * lex-min of the pair); the frontend re-orients per target / per displayed
 * bot. Drives form dots, the game-card grid, and the W-L-D record. `turns`
 * and the board are loaded lazily via `get_game_replay` when a card renders.
 */
export type TournamentMatchFinishedEvent = { tournament_id: number; player1_id: string; player2_id: string; repetition_index: number;
/**
 * Canonical player id occupying the Rat seat in this leg.
 */
rat_id: string; player1_score: number; player2_score: number; match_id: number }
/**
 * Emitted on every `MatchStarted` (slice B). Lets the matchup view show a
 * live-game row before the first turn arrives.
 */
export type TournamentMatchStartedEvent = { tournament_id: number; match_id: number; player1_id: string; player2_id: string; repetition_index: number }
/**
 * Emitted during the pre-tournament bot warmup, before the row exists (so it
 * carries no `tournament_id`). Drives a transient launch-side "Preparing
 * bots… (done/total)" state that clears when `TournamentStartedEvent` lands.
 * `done` increments before each bot's warmup and once more on completion.
 */
export type TournamentPreparingEvent = { done: number; total: number;
/**
 * The bot currently being warmed (agent_id), or `None` on the final
 * completion emit. Drives "Preparing {bot}…" so the line reads as progress
 * even while `done` sits at 0 during the first cold build.
 */
current: string | null }
/**
 * Attempt and slot counters shared by live events, snapshots, and history.
 */
export type TournamentProgress = { planned_slots: number; terminal_slots: number; successful_games: number; exhausted_slots: number; failed_attempts: number; running_matches: number }
/**
 * Complete reproducibility recipe for current rows. `None` on a snapshot
 * means the row predates durable provenance; readers must not fill it from
 * current defaults.
 */
export type TournamentProvenance = {
/**
 * Decimal string so CLI-created i64-range seeds remain exact across the
 * JavaScript boundary (which cannot represent every u64 as a number).
 */
tournament_seed: string; game_config_id: string; factory: GameFactoryConfig; games_per_matchup: number; mazes_per_matchup: number | null; max_failures_per_pair: number; seat_policy: StoredSeatPolicy; methodology: StoredTournamentMethodology; interpretation: StoredTournamentInterpretation; participants: StoredParticipantLaunchSpec[]; mutable_files_warning: string }
export type TournamentRuntimePhase = "idle" | "starting" | "running" | "stopping"
/**
 * App-owned runner state. Durable tournament lifecycle is projected
 * separately; this says which asynchronous generation still owns the slot.
 */
export type TournamentRuntimeStatus = { phase: TournamentRuntimePhase; tournament_id: number | null }
/**
 * Complete read model for one inspectable tournament. The same command
 * hydrates historical rows and reconciles an active event-fed view from
 * durable truth when lifecycle broadcasts lag.
 */
export type TournamentSnapshot = { tournament_id: number; name: string | null; format: string; target: string | null; anchor_id: string | null; running: boolean; lifecycle: TournamentLifecycleStatus; terminal: TournamentTerminalState | null; rating_readiness: RatingReadiness; rating_reason: string | null; paired: boolean;
/**
 * Absent only when an older tournament row did not record its execution
 * conditions. Optional in TypeScript so existing fixture consumers remain
 * compatible; current rows always include it.
 */
methodology?: StoredTournamentMethodology | null;
/**
 * Complete recipe for current rows. Absent on legacy rows rather than
 * synthesizing today's anchor, estimator, launch command, or defaults.
 */
provenance?: TournamentProvenance | null; created_at: string; started_at: string | null; terminal_at: string | null; last_finished_at: string | null; plan_summary: string; players: string[]; games_per_matchup: number; progress: TournamentProgress; standings: StandingRow[]; games: StoredFinishedGame[]; failures: StoredMatchFailure[]; slots: StoredTournamentSlot[];
/**
 * Run-level warning when successful attempts cannot be joined to their
 * saved final-position evidence. This is derived from the durable
 * attempts plus the replay directory on every snapshot, so write-time
 * failures remain visible after navigation or app restart without
 * changing the scored tournament outcome.
 */
inspection_warning: string | null }
/**
 * Emitted once, right after the tournament row is created. Scaffolds the
 * header, hero, and axis before any game finishes.
 */
export type TournamentStartedEvent = { tournament_id: number; name: string | null;
/**
 * "gauntlet" or "round_robin".
 */
format: string;
/**
 * In a gauntlet, the measured bot (highlighted, not clickable). `None`
 * for round-robin.
 */
target: string | null; total_games: number;
/**
 * Games per matchup (= 2 × mazes under the paired schedule). Configurable,
 * so the matchup view reads this instead of a hardcoded count.
 */
games_per_matchup: number;
/**
 * Adjacent repetitions are the two seat-swapped legs of one shared maze.
 */
paired: boolean;
/**
 * Configured executor concurrency. The live ETA uses the actual launch
 * conditions instead of assuming the default worker count.
 */
max_parallel: number; anchor_id: string;
/**
 * Shared-core provenance string, identical in the launch line and the
 * live header: e.g. "my-bot vs 6 (gauntlet) · tiny preset · 200 ms/move".
 */
plan_summary: string; players: PlayerLite[] }
/**
 * Immediate acknowledgement that cancellation was accepted. Terminal events
 * still arrive only after the owning supervisor drains and finalizes.
 */
export type TournamentStoppingEvent = { tournament_id: number | null }
/**
 * Row in the "in this store" panel.
 */
export type TournamentSummary = { id: number; name: string | null; format: string; created_at: string;
/**
 * The app-owned runner is currently executing this tournament. Separate
 * from durable lifecycle: navigation never owns runner lifetime.
 */
running: boolean; lifecycle: TournamentLifecycleStatus; terminal: TournamentTerminalState | null; rating_readiness: RatingReadiness; rating_reason: string | null; progress: TournamentProgress }
export type TournamentTerminalOutcome = "completed" | "completed_with_failures" | "user_stopped" | "infrastructure_failure"
export type TournamentTerminalState = { outcome: TournamentTerminalOutcome; reason: string | null; at: string }
/**
 * Per-turn delta. Walls/mud never change, so we only send positions + cheese.
 */
export type TurnPlayedEvent = { match_id: number; turn: number; state_hash: string; player1: PlayerState; player2: PlayerState; cheese: Coord[]; player1_action: Direction; player2_action: Direction }
export type WallEntry = { from: Coord; to: Coord }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
