// This file is auto-generated by specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getGameState(config: MatchConfigParams | null) : Promise<Result<MazeState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_state", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startMatch(player1Cmd: string, player2Cmd: string, player1WorkingDir: string | null, player2WorkingDir: string | null, config: MatchConfigParams | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_match", { player1Cmd, player2Cmd, player1WorkingDir, player2WorkingDir, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadBotConfigs() : Promise<Result<BotConfigEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_bot_configs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveBotConfigs(configs: BotConfigEntry[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_bot_configs", { configs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadMatchConfig() : Promise<Result<MatchConfigParams, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_match_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveMatchConfig(config: MatchConfigParams) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_match_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
botDisconnectedEvent: BotDisconnectedEvent,
botInfoEvent: BotInfoEvent,
matchErrorEvent: MatchErrorEvent,
matchOverEvent: MatchOverEvent,
matchStartedEvent: MatchStartedEvent,
turnPlayedEvent: TurnPlayedEvent
}>({
botDisconnectedEvent: "bot-disconnected-event",
botInfoEvent: "bot-info-event",
matchErrorEvent: "match-error-event",
matchOverEvent: "match-over-event",
matchStartedEvent: "match-started-event",
turnPlayedEvent: "turn-played-event"
})

/** user-defined constants **/



/** user-defined types **/

export type BotConfigEntry = { id: string; name: string; command: string; working_dir: string | null }
/**
 * Emitted when a bot disconnects mid-game.
 */
export type BotDisconnectedEvent = { match_id: number; player: PlayerSide; reason: string }
/**
 * Bot debug/analysis info forwarded from the host event stream.
 */
export type BotInfoEvent = { match_id: number; player: PlayerSide; turn: number; target: Coord | null; depth: number; nodes: number; score: number; path: Coord[]; message: string }
export type Coord = { x: number; y: number }
/**
 * Movement direction — specta-friendly mirror of pyrat_wire::Direction.
 */
export type Direction = "Up" | "Right" | "Down" | "Left" | "Stay"
export type MatchConfigParams = {
/**
 * Named preset, or "custom" for manual configuration.
 */
preset: string; width: number; height: number; max_turns: number; wall_density: number; mud_density: number; mud_range: number; connected: boolean; symmetric: boolean; cheese_count: number; cheese_symmetric: boolean;
/**
 * "corners" or "random".
 */
player_start: string;
/**
 * Seed for RNG. None = OS entropy.
 */
seed: number | null }
/**
 * Emitted on setup failures, bot crashes, etc.
 */
export type MatchErrorEvent = { match_id: number; message: string }
/**
 * Emitted when the match ends normally.
 */
export type MatchOverEvent = { match_id: number; winner: MatchWinner; player1_score: number; player2_score: number; turns_played: number }
/**
 * Full initial state so the frontend can initialize the renderer.
 */
export type MatchStartedEvent = { match_id: number; maze: MazeState }
export type MatchWinner = "Player1" | "Player2" | "Draw"
export type MazeState = { width: number; height: number; turn: number; max_turns: number; walls: WallEntry[]; mud: MudEntry[]; cheese: Coord[]; player1: PlayerState; player2: PlayerState; total_cheese: number }
export type MudEntry = { from: Coord; to: Coord; cost: number }
/**
 * Player identity — specta-friendly mirror of pyrat_wire::Player.
 */
export type PlayerSide = "Player1" | "Player2"
export type PlayerState = { position: Coord; score: number }
/**
 * Per-turn delta. Walls/mud never change, so we only send positions + cheese.
 */
export type TurnPlayedEvent = { match_id: number; turn: number; player1: PlayerState; player2: PlayerState; cheese: Coord[]; player1_action: Direction; player2_action: Direction }
export type WallEntry = { from: Coord; to: Coord }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
