# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Action(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Action()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Action
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Action
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Action
    def Player(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Action
    def Turn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Action
    def Provisional(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Action
    def ThinkMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ActionStart(builder):
    builder.StartObject(5)

def Start(builder):
    ActionStart(builder)

def ActionAddDirection(builder, direction):
    builder.PrependUint8Slot(0, direction, 0)

def AddDirection(builder, direction):
    ActionAddDirection(builder, direction)

def ActionAddPlayer(builder, player):
    builder.PrependUint8Slot(1, player, 0)

def AddPlayer(builder, player):
    ActionAddPlayer(builder, player)

def ActionAddTurn(builder, turn):
    builder.PrependUint16Slot(2, turn, 0)

def AddTurn(builder, turn):
    ActionAddTurn(builder, turn)

def ActionAddProvisional(builder, provisional):
    builder.PrependBoolSlot(3, provisional, 0)

def AddProvisional(builder, provisional):
    ActionAddProvisional(builder, provisional)

def ActionAddThinkMs(builder, thinkMs):
    builder.PrependUint32Slot(4, thinkMs, 0)

def AddThinkMs(builder, thinkMs):
    ActionAddThinkMs(builder, thinkMs)

def ActionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ActionEnd(builder)
