# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Advance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Advance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAdvance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Advance
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Advance
    def P1Dir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Advance
    def P2Dir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Advance
    def Turn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Advance
    def NewHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AdvanceStart(builder):
    builder.StartObject(4)

def Start(builder):
    AdvanceStart(builder)

def AdvanceAddP1Dir(builder, p1Dir):
    builder.PrependUint8Slot(0, p1Dir, 0)

def AddP1Dir(builder, p1Dir):
    AdvanceAddP1Dir(builder, p1Dir)

def AdvanceAddP2Dir(builder, p2Dir):
    builder.PrependUint8Slot(1, p2Dir, 0)

def AddP2Dir(builder, p2Dir):
    AdvanceAddP2Dir(builder, p2Dir)

def AdvanceAddTurn(builder, turn):
    builder.PrependUint16Slot(2, turn, 0)

def AddTurn(builder, turn):
    AdvanceAddTurn(builder, turn)

def AdvanceAddNewHash(builder, newHash):
    builder.PrependUint64Slot(3, newHash, 0)

def AddNewHash(builder, newHash):
    AdvanceAddNewHash(builder, newHash)

def AdvanceEnd(builder):
    return builder.EndObject()

def End(builder):
    return AdvanceEnd(builder)
