# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class BotMessage(object):
    NONE = 0
    Identify = 1
    Ready = 2
    PreprocessingDone = 3
    Action = 4
    Pong = 5
    Info = 6
    RenderCommands = 7
    Provisional = 8
    SyncOk = 9
    Resync = 10
