# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Configure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Configure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConfigure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Configure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Configure
    def Options(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from pyrat_sdk._wire.protocol.OptionAssignment import OptionAssignment
            obj = OptionAssignment()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Configure
    def OptionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Configure
    def OptionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Configure
    def MatchConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from pyrat_sdk._wire.protocol.MatchConfig import MatchConfig
            obj = MatchConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ConfigureStart(builder):
    builder.StartObject(2)

def Start(builder):
    ConfigureStart(builder)

def ConfigureAddOptions(builder, options):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(options), 0)

def AddOptions(builder, options):
    ConfigureAddOptions(builder, options)

def ConfigureStartOptionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOptionsVector(builder, numElems):
    return ConfigureStartOptionsVector(builder, numElems)

def ConfigureAddMatchConfig(builder, matchConfig):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(matchConfig), 0)

def AddMatchConfig(builder, matchConfig):
    ConfigureAddMatchConfig(builder, matchConfig)

def ConfigureEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConfigureEnd(builder)
