# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FullState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FullState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFullState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FullState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FullState
    def MatchConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from pyrat_sdk._wire.protocol.MatchConfig import MatchConfig
            obj = MatchConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FullState
    def TurnState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from pyrat_sdk._wire.protocol.TurnState import TurnState
            obj = TurnState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FullStateStart(builder):
    builder.StartObject(2)

def Start(builder):
    FullStateStart(builder)

def FullStateAddMatchConfig(builder, matchConfig):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(matchConfig), 0)

def AddMatchConfig(builder, matchConfig):
    FullStateAddMatchConfig(builder, matchConfig)

def FullStateAddTurnState(builder, turnState):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(turnState), 0)

def AddTurnState(builder, turnState):
    FullStateAddTurnState(builder, turnState)

def FullStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return FullStateEnd(builder)
