# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GameOver(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameOver()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameOver(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameOver
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GameOver
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GameOver
    def Player1Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GameOver
    def Player2Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def GameOverStart(builder):
    builder.StartObject(3)

def Start(builder):
    GameOverStart(builder)

def GameOverAddResult(builder, result):
    builder.PrependUint8Slot(0, result, 0)

def AddResult(builder, result):
    GameOverAddResult(builder, result)

def GameOverAddPlayer1Score(builder, player1Score):
    builder.PrependFloat32Slot(1, player1Score, 0.0)

def AddPlayer1Score(builder, player1Score):
    GameOverAddPlayer1Score(builder, player1Score)

def GameOverAddPlayer2Score(builder, player2Score):
    builder.PrependFloat32Slot(2, player2Score, 0.0)

def AddPlayer2Score(builder, player2Score):
    GameOverAddPlayer2Score(builder, player2Score)

def GameOverEnd(builder):
    return builder.EndObject()

def End(builder):
    return GameOverEnd(builder)
