# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GoPreprocess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GoPreprocess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGoPreprocess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GoPreprocess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GoPreprocess
    def StateHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def GoPreprocessStart(builder):
    builder.StartObject(1)

def Start(builder):
    GoPreprocessStart(builder)

def GoPreprocessAddStateHash(builder, stateHash):
    builder.PrependUint64Slot(0, stateHash, 0)

def AddStateHash(builder, stateHash):
    GoPreprocessAddStateHash(builder, stateHash)

def GoPreprocessEnd(builder):
    return builder.EndObject()

def End(builder):
    return GoPreprocessEnd(builder)
