# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GoState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GoState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGoState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GoState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GoState
    def TurnState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from pyrat_sdk._wire.protocol.TurnState import TurnState
            obj = TurnState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GoState
    def StateHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # GoState
    def Limits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from pyrat_sdk._wire.protocol.SearchLimits import SearchLimits
            obj = SearchLimits()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GoStateStart(builder):
    builder.StartObject(3)

def Start(builder):
    GoStateStart(builder)

def GoStateAddTurnState(builder, turnState):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(turnState), 0)

def AddTurnState(builder, turnState):
    GoStateAddTurnState(builder, turnState)

def GoStateAddStateHash(builder, stateHash):
    builder.PrependUint64Slot(1, stateHash, 0)

def AddStateHash(builder, stateHash):
    GoStateAddStateHash(builder, stateHash)

def GoStateAddLimits(builder, limits):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(limits), 0)

def AddLimits(builder, limits):
    GoStateAddLimits(builder, limits)

def GoStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return GoStateEnd(builder)
