# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

class HostMessage(object):
    NONE = 0
    SetOption = 1
    MatchConfig = 2
    StartPreprocessing = 3
    TurnState = 4
    Stop = 5
    Timeout = 6
    GameOver = 7
    Ping = 8
