# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Identify(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Identify()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdentify(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Identify
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Identify
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Identify
    def Author(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Identify
    def Options(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from pyrat_sdk._wire.protocol.OptionDef import OptionDef
            obj = OptionDef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Identify
    def OptionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Identify
    def OptionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Identify
    def AgentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def IdentifyStart(builder):
    builder.StartObject(4)

def Start(builder):
    IdentifyStart(builder)

def IdentifyAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    IdentifyAddName(builder, name)

def IdentifyAddAuthor(builder, author):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(author), 0)

def AddAuthor(builder, author):
    IdentifyAddAuthor(builder, author)

def IdentifyAddOptions(builder, options):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(options), 0)

def AddOptions(builder, options):
    IdentifyAddOptions(builder, options)

def IdentifyStartOptionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOptionsVector(builder, numElems):
    return IdentifyStartOptionsVector(builder, numElems)

def IdentifyAddAgentId(builder, agentId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(agentId), 0)

def AddAgentId(builder, agentId):
    IdentifyAddAgentId(builder, agentId)

def IdentifyEnd(builder):
    return builder.EndObject()

def End(builder):
    return IdentifyEnd(builder)
