# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Info(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Info()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Info
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Info
    def Player(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Info
    def Multipv(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Info
    def Target(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Info
    def Depth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Info
    def Nodes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Info
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # Info
    def Pv(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Info
    def PvAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Info
    def PvLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Info
    def PvIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Info
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InfoStart(builder):
    builder.StartObject(8)

def Start(builder):
    InfoStart(builder)

def InfoAddPlayer(builder, player):
    builder.PrependUint8Slot(0, player, 0)

def AddPlayer(builder, player):
    InfoAddPlayer(builder, player)

def InfoAddMultipv(builder, multipv):
    builder.PrependUint16Slot(1, multipv, 0)

def AddMultipv(builder, multipv):
    InfoAddMultipv(builder, multipv)

def InfoAddTarget(builder, target):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder, target):
    InfoAddTarget(builder, target)

def InfoAddDepth(builder, depth):
    builder.PrependUint16Slot(3, depth, 0)

def AddDepth(builder, depth):
    InfoAddDepth(builder, depth)

def InfoAddNodes(builder, nodes):
    builder.PrependUint32Slot(4, nodes, 0)

def AddNodes(builder, nodes):
    InfoAddNodes(builder, nodes)

def InfoAddScore(builder, score):
    builder.PrependFloat32Slot(5, score, None)

def AddScore(builder, score):
    InfoAddScore(builder, score)

def InfoAddPv(builder, pv):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(pv), 0)

def AddPv(builder, pv):
    InfoAddPv(builder, pv)

def InfoStartPvVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPvVector(builder, numElems):
    return InfoStartPvVector(builder, numElems)

def InfoAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    InfoAddMessage(builder, message)

def InfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return InfoEnd(builder)
