# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OptionDef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OptionDef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOptionDef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OptionDef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OptionDef
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OptionDef
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OptionDef
    def DefaultValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OptionDef
    def Min(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OptionDef
    def Max(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OptionDef
    def Choices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # OptionDef
    def ChoicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OptionDef
    def ChoicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def OptionDefStart(builder):
    builder.StartObject(6)

def Start(builder):
    OptionDefStart(builder)

def OptionDefAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    OptionDefAddName(builder, name)

def OptionDefAddType(builder, type):
    builder.PrependUint8Slot(1, type, 0)

def AddType(builder, type):
    OptionDefAddType(builder, type)

def OptionDefAddDefaultValue(builder, defaultValue):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(defaultValue), 0)

def AddDefaultValue(builder, defaultValue):
    OptionDefAddDefaultValue(builder, defaultValue)

def OptionDefAddMin(builder, min):
    builder.PrependInt32Slot(3, min, 0)

def AddMin(builder, min):
    OptionDefAddMin(builder, min)

def OptionDefAddMax(builder, max):
    builder.PrependInt32Slot(4, max, 0)

def AddMax(builder, max):
    OptionDefAddMax(builder, max)

def OptionDefAddChoices(builder, choices):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(choices), 0)

def AddChoices(builder, choices):
    OptionDefAddChoices(builder, choices)

def OptionDefStartChoicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChoicesVector(builder, numElems):
    return OptionDefStartChoicesVector(builder, numElems)

def OptionDefEnd(builder):
    return builder.EndObject()

def End(builder):
    return OptionDefEnd(builder)
