# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Pong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Pong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Pong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PongStart(builder):
    builder.StartObject(0)

def Start(builder):
    PongStart(builder)

def PongEnd(builder):
    return builder.EndObject()

def End(builder):
    return PongEnd(builder)
