# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Provisional(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Provisional()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProvisional(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Provisional
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Provisional
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Provisional
    def Player(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Provisional
    def Turn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Provisional
    def StateHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ProvisionalStart(builder):
    builder.StartObject(4)

def Start(builder):
    ProvisionalStart(builder)

def ProvisionalAddDirection(builder, direction):
    builder.PrependUint8Slot(0, direction, 0)

def AddDirection(builder, direction):
    ProvisionalAddDirection(builder, direction)

def ProvisionalAddPlayer(builder, player):
    builder.PrependUint8Slot(1, player, 0)

def AddPlayer(builder, player):
    ProvisionalAddPlayer(builder, player)

def ProvisionalAddTurn(builder, turn):
    builder.PrependUint16Slot(2, turn, 0)

def AddTurn(builder, turn):
    ProvisionalAddTurn(builder, turn)

def ProvisionalAddStateHash(builder, stateHash):
    builder.PrependUint64Slot(3, stateHash, 0)

def AddStateHash(builder, stateHash):
    ProvisionalAddStateHash(builder, stateHash)

def ProvisionalEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProvisionalEnd(builder)
