# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SearchLimits(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SearchLimits()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSearchLimits(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SearchLimits
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SearchLimits
    def TimeoutMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SearchLimits
    def Depth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # SearchLimits
    def Nodes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SearchLimitsStart(builder):
    builder.StartObject(3)

def Start(builder):
    SearchLimitsStart(builder)

def SearchLimitsAddTimeoutMs(builder, timeoutMs):
    builder.PrependUint32Slot(0, timeoutMs, 0)

def AddTimeoutMs(builder, timeoutMs):
    SearchLimitsAddTimeoutMs(builder, timeoutMs)

def SearchLimitsAddDepth(builder, depth):
    builder.PrependUint16Slot(1, depth, 0)

def AddDepth(builder, depth):
    SearchLimitsAddDepth(builder, depth)

def SearchLimitsAddNodes(builder, nodes):
    builder.PrependUint32Slot(2, nodes, 0)

def AddNodes(builder, nodes):
    SearchLimitsAddNodes(builder, nodes)

def SearchLimitsEnd(builder):
    return builder.EndObject()

def End(builder):
    return SearchLimitsEnd(builder)
