# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Timeout(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Timeout()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTimeout(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Timeout
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Timeout
    def DefaultMove(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def TimeoutStart(builder):
    builder.StartObject(1)

def Start(builder):
    TimeoutStart(builder)

def TimeoutAddDefaultMove(builder, defaultMove):
    builder.PrependUint8Slot(0, defaultMove, 0)

def AddDefaultMove(builder, defaultMove):
    TimeoutAddDefaultMove(builder, defaultMove)

def TimeoutEnd(builder):
    return builder.EndObject()

def End(builder):
    return TimeoutEnd(builder)
