# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TurnState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TurnState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTurnState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TurnState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TurnState
    def Turn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TurnState
    def Player1Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TurnState
    def Player2Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TurnState
    def Player1Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TurnState
    def Player2Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TurnState
    def Player1MudTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TurnState
    def Player2MudTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TurnState
    def Cheese(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 2
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TurnState
    def CheeseLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TurnState
    def CheeseIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # TurnState
    def Player1LastMove(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TurnState
    def Player2LastMove(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TurnState
    def StateHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TurnStateStart(builder):
    builder.StartObject(11)

def Start(builder):
    TurnStateStart(builder)

def TurnStateAddTurn(builder, turn):
    builder.PrependUint16Slot(0, turn, 0)

def AddTurn(builder, turn):
    TurnStateAddTurn(builder, turn)

def TurnStateAddPlayer1Position(builder, player1Position):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(player1Position), 0)

def AddPlayer1Position(builder, player1Position):
    TurnStateAddPlayer1Position(builder, player1Position)

def TurnStateAddPlayer2Position(builder, player2Position):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(player2Position), 0)

def AddPlayer2Position(builder, player2Position):
    TurnStateAddPlayer2Position(builder, player2Position)

def TurnStateAddPlayer1Score(builder, player1Score):
    builder.PrependFloat32Slot(3, player1Score, 0.0)

def AddPlayer1Score(builder, player1Score):
    TurnStateAddPlayer1Score(builder, player1Score)

def TurnStateAddPlayer2Score(builder, player2Score):
    builder.PrependFloat32Slot(4, player2Score, 0.0)

def AddPlayer2Score(builder, player2Score):
    TurnStateAddPlayer2Score(builder, player2Score)

def TurnStateAddPlayer1MudTurns(builder, player1MudTurns):
    builder.PrependUint8Slot(5, player1MudTurns, 0)

def AddPlayer1MudTurns(builder, player1MudTurns):
    TurnStateAddPlayer1MudTurns(builder, player1MudTurns)

def TurnStateAddPlayer2MudTurns(builder, player2MudTurns):
    builder.PrependUint8Slot(6, player2MudTurns, 0)

def AddPlayer2MudTurns(builder, player2MudTurns):
    TurnStateAddPlayer2MudTurns(builder, player2MudTurns)

def TurnStateAddCheese(builder, cheese):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(cheese), 0)

def AddCheese(builder, cheese):
    TurnStateAddCheese(builder, cheese)

def TurnStateStartCheeseVector(builder, numElems):
    return builder.StartVector(2, numElems, 1)

def StartCheeseVector(builder, numElems):
    return TurnStateStartCheeseVector(builder, numElems)

def TurnStateAddPlayer1LastMove(builder, player1LastMove):
    builder.PrependUint8Slot(8, player1LastMove, 0)

def AddPlayer1LastMove(builder, player1LastMove):
    TurnStateAddPlayer1LastMove(builder, player1LastMove)

def TurnStateAddPlayer2LastMove(builder, player2LastMove):
    builder.PrependUint8Slot(9, player2LastMove, 0)

def AddPlayer2LastMove(builder, player2LastMove):
    TurnStateAddPlayer2LastMove(builder, player2LastMove)

def TurnStateAddStateHash(builder, stateHash):
    builder.PrependUint64Slot(10, stateHash, 0)

def AddStateHash(builder, stateHash):
    TurnStateAddStateHash(builder, stateHash)

def TurnStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return TurnStateEnd(builder)
