[settings]
name = "Search.rs"
agent_id = "pyrat/search"
run_command = "cargo run --release"

[details]
description = "Iterative-deepening best-response tree search"
developer = "mintiti"
language = "Rust"
tags = ["search", "tree-search", "iterative-deepening"]
