class PyMoveUndo:
    @property
    def p1_pos(self) -> tuple[int, int]: ...
    @property
    def p2_pos(self) -> tuple[int, int]: ...
    @property
    def p1_target(self) -> tuple[int, int]: ...
    @property
    def p2_target(self) -> tuple[int, int]: ...
    @property
    def p1_mud(self) -> int: ...
    @property
    def p2_mud(self) -> int: ...
    @property
    def p1_score(self) -> float: ...
    @property
    def p2_score(self) -> float: ...
    @property
    def p1_misses(self) -> int: ...
    @property
    def p2_misses(self) -> int: ...
    @property
    def collected_cheese(self) -> list[tuple[int, int]]: ...
    @property
    def turn(self) -> int: ...

class PyGameState:
    def __init__(
        self,
        width: int | None = None,
        height: int | None = None,
        cheese_count: int | None = None,
        symmetric: bool = True,
        seed: int | None = None,
    ) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def turn(self) -> int: ...
    @property
    def max_turns(self) -> int: ...
    @property
    def player1_position(self) -> tuple[int, int]: ...
    @property
    def player2_position(self) -> tuple[int, int]: ...
    @property
    def player1_score(self) -> float: ...
    @property
    def player2_score(self) -> float: ...
    def cheese_positions(self) -> list[tuple[int, int]]: ...
    def mud_entries(self) -> list[tuple[tuple[int, int], tuple[int, int], int]]: ...
    def step(
        self, p1_move: int, p2_move: int
    ) -> tuple[bool, list[tuple[int, int]]]: ...
    def make_move(self, p1_move: int, p2_move: int) -> PyMoveUndo: ...
    def unmake_move(self, undo: PyMoveUndo) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
