"""Type stubs for the PyO3 `_engine` extension.

Mirrors the Rust pyclasses in `sdk/python/src/{sim,maze,codec}.rs`. Keep in
sync when the PyO3 surface changes, or mypy will see returns as Any and the
public typed surface in `state.py` / `bot.py` will leak `no-any-return`.
"""

from typing import Any

import numpy as np

# ── Tuples / aliases used in the codec ────────────────
_XY = tuple[int, int]
_PathTuple = tuple[_XY, list[int], list[int], int]

# ── codec functions ───────────────────────────────────
def parse_host_frame(buf: bytes) -> dict[str, Any]: ...
def parse_bot_frame(buf: bytes) -> dict[str, Any]: ...
def serialize_bot_msg(msg: dict[str, Any]) -> bytes: ...
def serialize_host_msg(msg: dict[str, Any]) -> bytes: ...

# ── MoveUndo ──────────────────────────────────────────
class MoveUndo:
    @property
    def p1_pos(self) -> _XY: ...
    @property
    def p2_pos(self) -> _XY: ...
    @property
    def p1_mud(self) -> int: ...
    @property
    def p2_mud(self) -> int: ...
    @property
    def p1_score(self) -> float: ...
    @property
    def p2_score(self) -> float: ...
    @property
    def p1_misses(self) -> int: ...
    @property
    def p2_misses(self) -> int: ...
    @property
    def collected_cheese(self) -> list[_XY]: ...
    @property
    def turn(self) -> int: ...

# ── GameSim ───────────────────────────────────────────
class GameSim:
    # No public constructor — created via PyMaze.to_sim.
    def make_move(self, p1_dir: int, p2_dir: int) -> MoveUndo: ...
    def unmake_move(self, undo: MoveUndo) -> None: ...
    def recompute_state_hash(self) -> None: ...
    def __copy__(self) -> GameSim: ...
    def __deepcopy__(self, memo: dict[Any, Any]) -> GameSim: ...
    @property
    def player1_position(self) -> _XY: ...
    @property
    def player2_position(self) -> _XY: ...
    @property
    def player1_score(self) -> float: ...
    @property
    def player2_score(self) -> float: ...
    @property
    def player1_mud_turns(self) -> int: ...
    @property
    def player2_mud_turns(self) -> int: ...
    @property
    def cheese_positions(self) -> list[_XY]: ...
    @property
    def turn(self) -> int: ...
    @property
    def max_turns(self) -> int: ...
    @property
    def is_game_over(self) -> bool: ...
    @property
    def state_hash(self) -> int: ...

# ── PyMaze ────────────────────────────────────────────
class PyMaze:
    def __init__(
        self,
        width: int,
        height: int,
        walls: list[tuple[_XY, _XY]],
        mud: list[tuple[_XY, _XY, int]],
    ) -> None: ...
    def neighbors(self, x: int, y: int) -> list[tuple[int, int, int]]: ...
    def edge_cost(self, x1: int, y1: int, x2: int, y2: int) -> int | None: ...
    def has_edge(self, x1: int, y1: int, x2: int, y2: int) -> bool: ...
    def effective_moves(self, x: int, y: int) -> list[int]: ...
    def move_cost(self, x: int, y: int, direction: int) -> int | None: ...
    def build_movement_matrix(self) -> np.ndarray: ...
    def shortest_path(self, start: _XY, goal: _XY) -> _PathTuple | None: ...
    def nearest_cheese(self, pos: _XY, cheese: list[_XY]) -> _PathTuple | None: ...
    def nearest_cheeses(self, pos: _XY, cheese: list[_XY]) -> list[_PathTuple]: ...
    def distances_from(self, pos: _XY) -> dict[_XY, int]: ...
    def to_sim(
        self,
        p1_pos: _XY,
        p2_pos: _XY,
        p1_score: float,
        p2_score: float,
        p1_mud: int,
        p2_mud: int,
        cheese: list[_XY],
        turn: int,
    ) -> GameSim: ...
