name: Feature Request
description: Suggest something new
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What's the situation today and why isn't it good enough?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen? Alternatives you considered?
    validations:
      required: false
