# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MatchConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatchConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMatchConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MatchConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MatchConfig
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MatchConfig
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MatchConfig
    def MaxTurns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # MatchConfig
    def Walls(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from pyrat_sdk._wire.protocol.Wall import Wall
            obj = Wall()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatchConfig
    def WallsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatchConfig
    def WallsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # MatchConfig
    def Mud(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from pyrat_sdk._wire.protocol.Mud import Mud
            obj = Mud()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatchConfig
    def MudLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatchConfig
    def MudIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # MatchConfig
    def Cheese(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 2
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatchConfig
    def CheeseLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatchConfig
    def CheeseIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # MatchConfig
    def Player1Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatchConfig
    def Player2Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatchConfig
    def ControlledPlayers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MatchConfig
    def ControlledPlayersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # MatchConfig
    def ControlledPlayersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatchConfig
    def ControlledPlayersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # MatchConfig
    def Timing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MatchConfig
    def MoveTimeoutMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MatchConfig
    def PreprocessingTimeoutMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MatchConfigStart(builder):
    builder.StartObject(12)

def Start(builder):
    MatchConfigStart(builder)

def MatchConfigAddWidth(builder, width):
    builder.PrependUint8Slot(0, width, 0)

def AddWidth(builder, width):
    MatchConfigAddWidth(builder, width)

def MatchConfigAddHeight(builder, height):
    builder.PrependUint8Slot(1, height, 0)

def AddHeight(builder, height):
    MatchConfigAddHeight(builder, height)

def MatchConfigAddMaxTurns(builder, maxTurns):
    builder.PrependUint16Slot(2, maxTurns, 0)

def AddMaxTurns(builder, maxTurns):
    MatchConfigAddMaxTurns(builder, maxTurns)

def MatchConfigAddWalls(builder, walls):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(walls), 0)

def AddWalls(builder, walls):
    MatchConfigAddWalls(builder, walls)

def MatchConfigStartWallsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWallsVector(builder, numElems):
    return MatchConfigStartWallsVector(builder, numElems)

def MatchConfigAddMud(builder, mud):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(mud), 0)

def AddMud(builder, mud):
    MatchConfigAddMud(builder, mud)

def MatchConfigStartMudVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMudVector(builder, numElems):
    return MatchConfigStartMudVector(builder, numElems)

def MatchConfigAddCheese(builder, cheese):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(cheese), 0)

def AddCheese(builder, cheese):
    MatchConfigAddCheese(builder, cheese)

def MatchConfigStartCheeseVector(builder, numElems):
    return builder.StartVector(2, numElems, 1)

def StartCheeseVector(builder, numElems):
    return MatchConfigStartCheeseVector(builder, numElems)

def MatchConfigAddPlayer1Start(builder, player1Start):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(player1Start), 0)

def AddPlayer1Start(builder, player1Start):
    MatchConfigAddPlayer1Start(builder, player1Start)

def MatchConfigAddPlayer2Start(builder, player2Start):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(player2Start), 0)

def AddPlayer2Start(builder, player2Start):
    MatchConfigAddPlayer2Start(builder, player2Start)

def MatchConfigAddControlledPlayers(builder, controlledPlayers):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(controlledPlayers), 0)

def AddControlledPlayers(builder, controlledPlayers):
    MatchConfigAddControlledPlayers(builder, controlledPlayers)

def MatchConfigStartControlledPlayersVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartControlledPlayersVector(builder, numElems):
    return MatchConfigStartControlledPlayersVector(builder, numElems)

def MatchConfigAddTiming(builder, timing):
    builder.PrependUint8Slot(9, timing, 0)

def AddTiming(builder, timing):
    MatchConfigAddTiming(builder, timing)

def MatchConfigAddMoveTimeoutMs(builder, moveTimeoutMs):
    builder.PrependUint32Slot(10, moveTimeoutMs, 0)

def AddMoveTimeoutMs(builder, moveTimeoutMs):
    MatchConfigAddMoveTimeoutMs(builder, moveTimeoutMs)

def MatchConfigAddPreprocessingTimeoutMs(builder, preprocessingTimeoutMs):
    builder.PrependUint32Slot(11, preprocessingTimeoutMs, 0)

def AddPreprocessingTimeoutMs(builder, preprocessingTimeoutMs):
    MatchConfigAddPreprocessingTimeoutMs(builder, preprocessingTimeoutMs)

def MatchConfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return MatchConfigEnd(builder)
