# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RenderCommands(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RenderCommands()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRenderCommands(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RenderCommands
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RenderCommandsStart(builder):
    builder.StartObject(0)

def Start(builder):
    RenderCommandsStart(builder)

def RenderCommandsEnd(builder):
    return builder.EndObject()

def End(builder):
    return RenderCommandsEnd(builder)
