# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Wall(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Wall()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Wall
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Wall
    def Pos1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Wall
    def Pos2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from pyrat_sdk._wire.protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WallStart(builder):
    builder.StartObject(2)

def Start(builder):
    WallStart(builder)

def WallAddPos1(builder, pos1):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pos1), 0)

def AddPos1(builder, pos1):
    WallAddPos1(builder, pos1)

def WallAddPos2(builder, pos2):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pos2), 0)

def AddPos2(builder, pos2):
    WallAddPos2(builder, pos2)

def WallEnd(builder):
    return builder.EndObject()

def End(builder):
    return WallEnd(builder)
