from pyrat_engine._core.game import PyRat
from pyrat_engine._core.types import Coordinates, Mud, Wall

class GameConfig:
    @staticmethod
    def preset(name: str) -> GameConfig: ...
    @staticmethod
    def classic(width: int, height: int, cheese: int) -> GameConfig: ...
    def create(self, seed: int | None = None) -> PyRat: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def max_turns(self) -> int: ...

class GameBuilder:
    def __init__(self, width: int, height: int) -> None: ...
    def with_classic_maze(self) -> GameBuilder: ...
    def with_open_maze(self) -> GameBuilder: ...
    def with_random_maze(
        self,
        *,
        wall_density: float = 0.7,
        mud_density: float = 0.1,
        mud_range: int = 3,
        connected: bool = True,
        symmetric: bool = True,
    ) -> GameBuilder: ...
    def with_custom_maze(
        self,
        walls: list[Wall] | list[tuple[tuple[int, int], tuple[int, int]]],
        mud: list[Mud] | list[tuple[tuple[int, int], tuple[int, int], int]] = [],
    ) -> GameBuilder: ...
    def with_corner_positions(self) -> GameBuilder: ...
    def with_random_positions(self) -> GameBuilder: ...
    def with_custom_positions(
        self,
        p1: Coordinates | tuple[int, int],
        p2: Coordinates | tuple[int, int],
    ) -> GameBuilder: ...
    def with_random_cheese(self, count: int, symmetric: bool = True) -> GameBuilder: ...
    def with_custom_cheese(
        self,
        positions: list[Coordinates] | list[tuple[int, int]],
    ) -> GameBuilder: ...
    def with_max_turns(self, max_turns: int) -> GameBuilder: ...
    def build(self) -> GameConfig: ...
