from pyrat_engine._core.game import PyRat
from pyrat_engine._core.types import Coordinates, Mud, Wall

class PyGameConfigBuilder:
    def __init__(self, width: int, height: int) -> None: ...
    def with_walls(
        self, walls: list[Wall] | list[tuple[tuple[int, int], tuple[int, int]]]
    ) -> PyGameConfigBuilder: ...
    def with_mud(
        self, mud: list[Mud] | list[tuple[tuple[int, int], tuple[int, int], int]]
    ) -> PyGameConfigBuilder: ...
    def with_cheese(
        self, cheese: list[Coordinates] | list[tuple[int, int]]
    ) -> PyGameConfigBuilder: ...
    def with_player1_pos(
        self, pos: Coordinates | tuple[int, int]
    ) -> PyGameConfigBuilder: ...
    def with_player2_pos(
        self, pos: Coordinates | tuple[int, int]
    ) -> PyGameConfigBuilder: ...
    def with_max_turns(self, max_turns: int) -> PyGameConfigBuilder: ...
    def build(self) -> PyRat: ...
