from pyrat_engine._core.observation import PyGameObservation
from pyrat_engine._core.types import Coordinates, Mud, Wall

class PyMoveUndo:
    @property
    def p1_pos(self) -> Coordinates: ...
    @property
    def p2_pos(self) -> Coordinates: ...
    @property
    def p1_target(self) -> Coordinates: ...
    @property
    def p2_target(self) -> Coordinates: ...
    @property
    def p1_mud(self) -> int: ...
    @property
    def p2_mud(self) -> int: ...
    @property
    def p1_score(self) -> float: ...
    @property
    def p2_score(self) -> float: ...
    @property
    def p1_misses(self) -> int: ...
    @property
    def p2_misses(self) -> int: ...
    @property
    def collected_cheese(self) -> list[Coordinates]: ...
    @property
    def turn(self) -> int: ...

class PyRat:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def turn(self) -> int: ...
    @property
    def max_turns(self) -> int: ...
    @property
    def player1_position(self) -> Coordinates: ...
    @property
    def player2_position(self) -> Coordinates: ...
    @property
    def player1_score(self) -> float: ...
    @property
    def player2_score(self) -> float: ...
    @property
    def player1_mud_turns(self) -> int: ...
    @property
    def player2_mud_turns(self) -> int: ...
    def cheese_positions(self) -> list[Coordinates]: ...
    def mud_entries(self) -> list[Mud]: ...
    def wall_entries(self) -> list[Wall]: ...
    def get_valid_moves(self, pos: Coordinates | tuple[int, int]) -> list[int]: ...
    def effective_actions(self, pos: Coordinates | tuple[int, int]) -> list[int]: ...
    def effective_actions_p1(self) -> list[int]: ...
    def effective_actions_p2(self) -> list[int]: ...
    def step(self, p1_move: int, p2_move: int) -> tuple[bool, list[Coordinates]]: ...
    def make_move(self, p1_move: int, p2_move: int) -> PyMoveUndo: ...
    def unmake_move(self, undo: PyMoveUndo) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
    def get_observation(self, is_player_one: bool) -> PyGameObservation: ...
