import numpy as np
from pyrat_engine._core.game import PyRat
from pyrat_engine._core.types import Coordinates

class PyGameObservation:
    @property
    def player_position(self) -> Coordinates: ...
    @property
    def player_mud_turns(self) -> int: ...
    @property
    def player_score(self) -> float: ...
    @property
    def opponent_position(self) -> Coordinates: ...
    @property
    def opponent_mud_turns(self) -> int: ...
    @property
    def opponent_score(self) -> float: ...
    @property
    def current_turn(self) -> int: ...
    @property
    def max_turns(self) -> int: ...
    @property
    def cheese_matrix(self) -> np.ndarray[tuple[int, ...], np.dtype[np.uint8]]: ...
    @property
    def movement_matrix(self) -> np.ndarray[tuple[int, ...], np.dtype[np.int8]]: ...

class PyObservationHandler:
    def __init__(self, game: PyRat) -> None: ...
    def update_collected_cheese(self, collected: list[tuple[int, int]]) -> None: ...
    def refresh_cheese(self, game: PyRat) -> None: ...
    def get_observation(
        self, game: PyRat, is_player_one: bool
    ) -> PyGameObservation: ...
