// Prevents additional console window on Windows in release.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod commands;
mod events;
mod match_runner;
mod state;

use commands::{get_game_state, start_match};
use events::{
    BotDisconnectedEvent, MatchErrorEvent, MatchOverEvent, MatchStartedEvent, TurnPlayedEvent,
};
use tauri_specta::{collect_commands, collect_events, Builder};

fn main() {
    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![get_game_state, start_match])
        .events(collect_events![
            MatchStartedEvent,
            TurnPlayedEvent,
            MatchOverEvent,
            MatchErrorEvent,
            BotDisconnectedEvent
        ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// This file is auto-generated by specta. Do not edit."),
            "../src/bindings/generated.ts",
        )
        .expect("failed to export typescript bindings");

    tauri::Builder::default()
        .manage(state::AppState::default())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
