// Prevents additional console window on Windows in release.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod bot_config;
mod commands;
mod events;
mod json_store;
mod match_config;
mod match_runner;
mod state;

use bot_config::{load_bot_configs, save_bot_configs};
use commands::{get_game_state, start_match, stop_match};
use events::{
    BotDisconnectedEvent, BotInfoEvent, MatchErrorEvent, MatchOverEvent, MatchStartedEvent,
    TurnPlayedEvent,
};
use match_config::{load_match_config, save_match_config};
use tauri_specta::{collect_commands, collect_events, Builder};

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "pyrat_gui=debug,pyrat_host=debug,warn".parse().unwrap()),
        )
        .init();

    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            get_game_state,
            start_match,
            stop_match,
            load_bot_configs,
            save_bot_configs,
            load_match_config,
            save_match_config
        ])
        .events(collect_events![
            MatchStartedEvent,
            TurnPlayedEvent,
            MatchOverEvent,
            MatchErrorEvent,
            BotDisconnectedEvent,
            BotInfoEvent
        ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// This file is auto-generated by specta. Do not edit."),
            "../src/bindings/generated.ts",
        )
        .expect("failed to export typescript bindings");

    tauri::Builder::default()
        .manage(state::AppState::default())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
