name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    uses: ./.github/workflows/rust.yml

  test:
    uses: ./.github/workflows/test.yml
